[package]
name = "Evolvio"
version = "1.0.0"
description = "Evolvio — Track your habits. Transform your life."
authors = ["EVOLVIO Team"]
license = "MIT"
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6", features = ["notification-all", "shell-open", "window-all", "fs-read-file", "fs-write-file", "fs-read-dir", "fs-create-dir"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
